---
- name: Update all Linux nodes
  hosts: all
  become: yes
  serial: 2  # Process only 2 servers at a time
  tasks:
    - name: Update package manager cache (Debian-based)
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
      timeout: 600  # 10 minutes timeout
      retries: 3    # Retry up to 3 times if it fails
      delay: 5      # 5-second delay between retries
      ignore_errors: yes  # Skip if it fails after retries

    - name: Upgrade all packages (Debian-based)
      ansible.builtin.apt:
        upgrade: dist
      when: ansible_os_family == "Debian"
      timeout: 3600  # 1 hour timeout
      retries: 3     # Retry up to 3 times if it fails
      delay: 5       # 5-second delay between retries
      ignore_errors: yes  # Skip if it fails after retries

    - name: Upgrade all packages (RHEL-based)
      ansible.builtin.yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"
      timeout: 3600  # 1 hour timeout
      retries: 3     # Retry up to 3 times if it fails
      delay: 5       # 5-second delay between retries
      ignore_errors: yes  # Skip if it fails after retries

    - name: Upgrade all packages (Fedora-based)
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_distribution == "Fedora"
      timeout: 3600  # 1 hour timeout
      retries: 3     # Retry up to 3 times if it fails
      delay: 5       # 5-second delay between retries
      ignore_errors: yes  # Skip if it fails after retries

    - name: Pause between batches
      ansible.builtin.pause:
        seconds: 30  # 30-second delay before starting the next batch of 2 servers
      when: ansible_play_batch[-1] == inventory_hostname  # Only run on the last host of the batch
