---
- name: Reboot servers if needed
  hosts: all
  become: yes
  tasks:
    - name: Check if a reboot is required (Debian-based)
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required
      when: ansible_os_family == "Debian"

    - name: Reboot if required (Debian-based)
      ansible.builtin.reboot:
        msg: "Rebooting after updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: ansible_os_family == "Debian" and reboot_required.stat.exists

    - name: Reboot all RHEL-based systems
      ansible.builtin.reboot:
        msg: "Rebooting after updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: ansible_os_family == "RedHat"

    - name: Reboot all Fedora-based systems
      ansible.builtin.reboot:
        msg: "Rebooting after updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: ansible_distribution == "Fedora"
